
services:
  server:
    build:
      context: .
    ports:
      - 8080:80

  # SQL Server DB
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SqlPassword123!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
    driver: local
